### ISSUE TITLE
Broken link in the sources page

### ISSUE THREAD

**Issue by nicopace** [digitalmemex/dm4-migration-control#1]
There is a link that points to the 'Global Detention Project' and it is not working.

It is being provided by this JSON request: https://migrationcontrol.taz.de/migrationcontrol/v1/en/imprint/

Where it says this:

<pre>
{id: 57306, name: "Sources",…}
id
:
57306
name
:
"Sources"
text
:
"<p>Most of the used data has been extracted from official UNHCR materials. That includes, but is not limited to fact sheet data on refugees in as well as outside the countries and internally displaced persons. UNDP kindly made its data on the Human Development Index (HDI) available to us. Eurostats data has been used to calculate the acceptance quota of asylum requests within the EU. The World Bank is our source for data on remittances from refugees and migrants. Official development aid numbers have been provided by the OECD.</p>↵↵<p>Funds as displayed on the intro map are those labeled by the EU and/or EU member states to be given in the context of the prevention of irregular migration. Not all these funds are spent on border protection and the like, we added those who are given for unrelated projects but under the agreement that the receiving states work on migration control. The year of approval and only the main recipients are shown on the map. At some instances not all approved funds have been released. The numbers are very likely not complete.</p>↵↵<p>Source for the map with detention centers is the <a href=“http://www.globaldetentionproject.org/“>Global Detention Project</a></p>↵↵<p>Readmission agreements follow the collection of <a href=“http://irmcmaghreb.academia.edu/JeanPierreCassarino“>Prof. Jean Pierre Cassarino.</a></p>"
</pre>

it should say:

<pre>
{id: 57306, name: "Sources",…}
id
:
57306
name
:
"Sources"
text
:
"<p>Most of the used data has been extracted from official UNHCR materials. That includes, but is not limited to fact sheet data on refugees in as well as outside the countries and internally displaced persons. UNDP kindly made its data on the Human Development Index (HDI) available to us. Eurostats data has been used to calculate the acceptance quota of asylum requests within the EU. The World Bank is our source for data on remittances from refugees and migrants. Official development aid numbers have been provided by the OECD.</p>↵↵<p>Funds as displayed on the intro map are those labeled by the EU and/or EU member states to be given in the context of the prevention of irregular migration. Not all these funds are spent on border protection and the like, we added those who are given for unrelated projects but under the agreement that the receiving states work on migration control. The year of approval and only the main recipients are shown on the map. At some instances not all approved funds have been released. The numbers are very likely not complete.</p>↵↵<p>Source for the map with detention centers is the <a href='http://www.globaldetentionproject.org/'>Global Detention Project</a></p>↵↵<p>Readmission agreements follow the collection of <a href=“http://irmcmaghreb.academia.edu/JeanPierreCassarino“>Prof. Jean Pierre Cassarino.</a></p>"

</pre>

(Mind the single quotes instead of the double quotes.

**Comment by gu-stav** [comment]
@nicopace Thanks for the report! I fixed the links - will be deployed very soon! 🙏
